version: 2
jobs:
  check:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run ci-check

  test:
    parallelism: 3
    working_directory: ~/tmp
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Jest Suite
          command: npm run ci-test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit

  deploy:
    docker:
      - image: circleci/node:9
    working_directory: /tmp/deploy
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:NMQuy1v0qJO6f6FVfPIr2H8kgDtvXgJ7WpyrQAgnMP0"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://git.heroku.com/funfunautomator.git HEAD:refs/heads/master

workflows:
  version: 2
  build:
    jobs:
      - test
      - check
      - deploy:  # only deploy when master successfully builds
          requires:
            - test
            - check
          filters:
            branches:
              only: master